export interface McuItem {
  id: string;
  titleJa: string;
  titleEn: string;
  type: 'movie' | 'drama' | 'special';
  releaseDate: string; // YYYY-MM-DD
  releaseOrder: number;
  chronoOrder: number;
  chronoSetting: string;
  phase: number;
  importance: 1 | 2 | 3; // 3: 必須(根幹), 2: 推奨(キャラ理解), 1: 補足(ファン向け)
  importanceReason: string;
  synopsis: string;
  directorOrCreator: string;
  durationOrEpisodes: string; // 2時間6分, 全6話, etc.
  officialUrl?: string;
  explanationUrlQuery: string;
}

export const mcuItems: McuItem[] = [
  // --- PHASE 1 ---
  {
    id: 'iron_man',
    titleJa: 'アイアンマン',
    titleEn: 'Iron Man',
    type: 'movie',
    releaseDate: '2008-05-02',
    releaseOrder: 1,
    chronoOrder: 3,
    chronoSetting: '2010年（トニー誘拐〜アイアンマン誕生）',
    phase: 1,
    importance: 3,
    importanceReason: 'MCUすべての始まりであり、トニー・スターク（アイアンマン）の原点を描く最重要作。',
    synopsis: '実業家であり天才技術者のトニー・スタークは、テロ組織に拉致されたことを機にハイテクスーツを開発。自ら「アイアンマン」となり、世界の平和を守るために戦うことを決意する。',
    directorOrCreator: 'ジョン・ファヴロー',
    durationOrEpisodes: '2時間6分',
    officialUrl: 'https://marvel.disney.co.jp/movie/ironman',
    explanationUrlQuery: 'アイアンマン ネタバレ 考察 伏線'
  },
  {
    id: 'incredible_hulk',
    titleJa: 'インクレディブル・ハルク',
    titleEn: 'The Incredible Hulk',
    type: 'movie',
    releaseDate: '2008-06-13',
    releaseOrder: 2,
    chronoOrder: 5,
    chronoSetting: '2011年（アイアンマン2と同時期）',
    phase: 1,
    importance: 1,
    importanceReason: 'ブルース・バナー（ハルク）の出自。キャスト変更（エドワード・ノートンからマーク・ラファロ）があるが重要な世界観を共有。',
    synopsis: 'ガンマ線を浴びて怒ると怪力巨人に変身する身体となった科学者ブルース・バナー。軍の追跡から逃れながら治療法を探すが、強大な敵アボミネーションが出現する。',
    directorOrCreator: 'ルイ・レテリエ',
    durationOrEpisodes: '1時間52分',
    officialUrl: 'https://marvel.disney.co.jp/movie/incrediblehulk',
    explanationUrlQuery: 'インクレディブルハルク ネタバレ 考察 伏線'
  },
  {
    id: 'iron_man_2',
    titleJa: 'アイアンマン2',
    titleEn: 'Iron Man 2',
    type: 'movie',
    releaseDate: '2010-05-07',
    releaseOrder: 3,
    chronoOrder: 4,
    chronoSetting: '2011年（ハルク、マイティ・ソーと同時期）',
    phase: 1,
    importance: 2,
    importanceReason: 'ブラック・ウィドウやウォーマシンの初登場、アベンジャーズへの布石が散りばめられた一作。',
    synopsis: '自ら正体を明かしたトニーの前に、アーク・リアクター技術を自らのものとした宿敵ウィップラッシュが現れる。トニーは身体を蝕むパラジウム毒とも戦うことになる。',
    directorOrCreator: 'ジョン・ファヴロー',
    durationOrEpisodes: '2時間4分',
    officialUrl: 'https://marvel.disney.co.jp/movie/ironman2',
    explanationUrlQuery: 'アイアンマン2 ネタバレ 考察 伏線'
  },
  {
    id: 'thor',
    titleJa: 'マイティ・ソー',
    titleEn: 'Thor',
    type: 'movie',
    releaseDate: '2011-05-06',
    releaseOrder: 4,
    chronoOrder: 6,
    chronoSetting: '2011年（アイアンマン2の直後）',
    phase: 1,
    importance: 3,
    importanceReason: '神の世界「アスガルド」とソーの紹介、最重要ヴィラン「ロキ」の初登場作。',
    synopsis: '傲慢さゆえに地球へと追放され、力を失った雷神ソー。地球でジェーンらと出会い、謙虚さと真の勇気を学ぶ中、裏切り者の義弟ロキが地球へ刺客を送り込む。',
    directorOrCreator: 'ケネス・ブラナー',
    durationOrEpisodes: '1時間55分',
    officialUrl: 'https://marvel.disney.co.jp/movie/thor',
    explanationUrlQuery: 'マイティソー ネタバレ 考察 ロキ 結末'
  },
  {
    id: 'captain_america_tfa',
    titleJa: 'キャプテン・アメリカ/ザ・ファースト・アベンジャー',
    titleEn: 'Captain America: The First Avenger',
    type: 'movie',
    releaseDate: '2011-07-22',
    releaseOrder: 5,
    chronoOrder: 1,
    chronoSetting: '1942年 - 1945年（第二次世界大戦中）',
    phase: 1,
    importance: 3,
    importanceReason: '超人兵士にしてアベンジャーズのリーダー、スティーブ・ロジャースの起源。時系列順で見ると最も過去。',
    synopsis: '病弱だが愛国心と正義感にあふれる青年スティーブが、「スーパーソルジャー計画」で強靭な肉体を得て「キャプテン・アメリカ」となる。四次元キューブを狙うヒドラと決戦に挑み、氷の海に消える。',
    directorOrCreator: 'ジョー・ジョンストン',
    durationOrEpisodes: '2時間4分',
    officialUrl: 'https://marvel.disney.co.jp/movie/captain-america',
    explanationUrlQuery: 'キャプテンアメリカ ファーストアベンジャー ネタバレ 考察'
  },
  {
    id: 'avengers',
    titleJa: 'アベンジャーズ',
    titleEn: 'The Avengers',
    type: 'movie',
    releaseDate: '2012-05-04',
    releaseOrder: 6,
    chronoOrder: 7,
    chronoSetting: '2012年（ニューヨーク決戦）',
    phase: 1,
    importance: 3,
    importanceReason: 'ヒーローたちが初めて集結（結成）するフェーズ1の集大成。サノスの存在もここで初示唆。',
    synopsis: '地球征服を企むロキが四次元キューブを強奪し、宇宙からの軍隊を地球に呼び寄せる。S.H.I.E.L.D.長官フューリーの元、アイアンマン、キャプテン・アメリカ、ソー、ハルクらが人類の盾として集結する。',
    directorOrCreator: 'ジョス・ウェドン',
    durationOrEpisodes: '2時間23分',
    officialUrl: 'https://marvel.disney.co.jp/movie/avengers',
    explanationUrlQuery: 'アベンジャーズ1 ニューヨーク決戦 ネタバレ 考察'
  },

  // --- PHASE 2 ---
  {
    id: 'iron_man_3',
    titleJa: 'アイアンマン3',
    titleEn: 'Iron Man 3',
    type: 'movie',
    releaseDate: '2013-05-03',
    releaseOrder: 7,
    chronoOrder: 8,
    chronoSetting: '2012年 冬（ニューヨーク決戦から数ヶ月後）',
    phase: 2,
    importance: 2,
    importanceReason: 'ニューヨーク決戦でPTSDとなったトニーの成長劇。アベンジャーズ後のヒーロー個人が直面する苦悩を描く。',
    synopsis: 'アベンジャーズの戦闘後、不眠症とスーツ開発への依存に陥ったトニー。そこへ謎のテロリスト「マンダリン」が現れ、トニーの私生活や最愛のペッパーを標的に攻撃を開始する。',
    directorOrCreator: 'シェーン・ブラック',
    durationOrEpisodes: '2時間10分',
    officialUrl: 'https://marvel.disney.co.jp/movie/ironman3',
    explanationUrlQuery: 'アイアンマン3 ネタバレ 考察 ラストの意味'
  },
  {
    id: 'thor_dark_world',
    titleJa: 'マイティ・ソー/ダーク・ワールド',
    titleEn: 'Thor: The Dark World',
    type: 'movie',
    releaseDate: '2013-11-08',
    releaseOrder: 8,
    chronoOrder: 9,
    chronoSetting: '2013年（ロキが幽閉されたアスガルド）',
    phase: 2,
    importance: 2,
    importanceReason: 'インフィニティ・ストーンの1つ「エーテル（リアリティ・ストーン）」が物語の中心となる重要作。',
    synopsis: 'ダーク・エルフの生き残りマレキスが、宇宙を再び闇に包むためにエーテル（赤い謎の液体）を狙う。宿主となってしまった科学者ジェーンを救うため、ソーは宿敵であるロキと再び手を組む。',
    directorOrCreator: 'アラン・テイラー',
    durationOrEpisodes: '108分',
    officialUrl: 'https://marvel.disney.co.jp/movie/thor-dy',
    explanationUrlQuery: 'マイティソー ダークワールド ネタバレ 考察 ポストクレジット'
  },
  {
    id: 'captain_america_ws',
    titleJa: 'キャプテン・アメリカ/ウィンター・ソルジャー',
    titleEn: 'Captain America: The Winter Soldier',
    type: 'movie',
    releaseDate: '2014-04-04',
    releaseOrder: 9,
    chronoOrder: 10,
    chronoSetting: '2014年（S.H.I.E.L.D.の崩壊）',
    phase: 2,
    importance: 3,
    importanceReason: 'S.H.I.E.L.D.の崩壊、親友バッキーの再登場、後のインフィニティ・ウォーやシビル・ウォーの土台となる極めて評価の高い傑作。',
    synopsis: '現代に生きるキャプテン・アメリカは、S.H.I.E.L.D.に潜む恐るべき陰謀に気づく。追われる身となった彼は、ブラック・ウィドウ、ファルコンらと共に、伝説の暗殺者「ウィンター・ソルジャー」と対峙する。',
    directorOrCreator: 'アンソニー＆ジョー・ルッソ',
    durationOrEpisodes: '2時間16分',
    officialUrl: 'https://marvel.disney.co.jp/movie/captain-america2',
    explanationUrlQuery: 'キャプテンアメリカ ウィンターソルジャー ネタバレ 考察 結末'
  },
  {
    id: 'guardians_of_the_galaxy',
    titleJa: 'ガーディアンズ・オブ・ギャラクシー',
    titleEn: 'Guardians of the Galaxy',
    type: 'movie',
    releaseDate: '2014-08-01',
    releaseOrder: 10,
    chronoOrder: 11,
    chronoSetting: '2014年（地球を遠く離れた宇宙）',
    phase: 2,
    importance: 3,
    importanceReason: '宇宙を舞台にした個性豊かな「ガーディアンズ」を紹介。オーブ「パワー・ストーン」が回収される。',
    synopsis: '幼い頃に地球から拉致されたトレジャーハンター「スター・ロード」ことピーター・クイルは、謎の球体オーブを盗んだことで賞金稼ぎや暗殺者に追われ、偶然意気投合して宇宙最凶チームを結成する。',
    directorOrCreator: 'ジェームズ・ガン',
    durationOrEpisodes: '2時間1分',
    officialUrl: 'https://marvel.disney.co.jp/movie/gog',
    explanationUrlQuery: 'ガーディアンズオブギャラクシー1 ネタバレ 考察 曲'
  },
  {
    id: 'guardians_of_the_galaxy_vol2',
    titleJa: 'ガーディアンズ・オブ・ギャラクシー:リミックス',
    titleEn: 'Guardians of the Galaxy Vol. 2',
    type: 'movie',
    releaseDate: '2017-05-05', // Note: released in Phase 3 but chronologically right after Vol. 1
    releaseOrder: 15,
    chronoOrder: 12,
    chronoSetting: '2014年（前作の数ヶ月後）',
    phase: 3,
    importance: 2,
    importanceReason: 'ピーターの出自である天界人エゴを軸に進む。ベビー・グルートなど家族の「絆」を深める一作。',
    synopsis: 'ならず者集団「ガーディアンズ」は宇宙の救世主として名を馳せるが、ある依頼から黄金の種族ソヴリンに追われる。そこへピーターの父親と名乗る神のごとき男「エゴ」が現れる。',
    directorOrCreator: 'ジェームズ・ガン',
    durationOrEpisodes: '2時間16分',
    officialUrl: 'https://marvel.disney.co.jp/movie/gog-remix',
    explanationUrlQuery: 'ガーディアンズオブギャラクシー リミックス ネタバレ 考察 ヨンドゥ'
  },
  {
    id: 'avengers_aou',
    titleJa: 'アベンジャーズ/エイジ・オブ・ウルトロン',
    titleEn: 'Avengers: Age of Ultron',
    type: 'movie',
    releaseDate: '2015-05-01',
    releaseOrder: 11,
    chronoOrder: 13,
    chronoSetting: '2015年（ウルトロン計画とソコヴィア壊滅）',
    phase: 2,
    importance: 3,
    importanceReason: 'スカーレット・ウィッチ（ワンダ）、ヴィジョンらが初参戦。ソコヴィアでの事変が今後のヒーロー分断の原因となる。',
    synopsis: '平和を守るための平和維持AI「ウルトロン」をトニーが開発したが、AIは「人類滅亡こそが真の平和」と判断して暴走。アベンジャーズはこのかつてない絶望的な世界危機を食い止めるため共闘する。',
    directorOrCreator: 'ジョス・ウェドン',
    durationOrEpisodes: '2.5時間',
    officialUrl: 'https://marvel.disney.co.jp/movie/avengers-aou',
    explanationUrlQuery: 'アベンジャーズ エイジオブウルトロン ネタバレ 考察 ソコヴィア'
  },
  {
    id: 'ant_man',
    titleJa: 'アントマン',
    titleEn: 'Ant-Man',
    type: 'movie',
    releaseDate: '2015-07-17',
    releaseOrder: 12,
    chronoOrder: 14,
    chronoSetting: '2015年（フェーズ2の締めくくり）',
    phase: 2,
    importance: 2,
    importanceReason: 'サイズを変える最小ヒーロー、スコット・ラングの物語。後のエンドゲームに関わる「量子世界」の基本ルールを導入。',
    synopsis: '職ナシ、カネナシのバツイチ男スコット・ラングは、かつての天才科学者ピム博士から、体を1.5cmに縮小できる特殊スーツを託され、「アントマン」として新たな第一歩を踏み出す。',
    directorOrCreator: 'ペイトン・リード',
    durationOrEpisodes: '1時間57分',
    officialUrl: 'https://marvel.disney.co.jp/movie/antman',
    explanationUrlQuery: 'アントマン1 ネタバレ 考察 量子世界'
  },

  // --- PHASE 3 ---
  {
    id: 'captain_america_cw',
    titleJa: 'シビル・ウォー/キャプテン・アメリカ',
    titleEn: 'Captain America: Civil War',
    type: 'movie',
    releaseDate: '2016-05-06',
    releaseOrder: 13,
    chronoOrder: 15,
    chronoSetting: '2016年（ヒーローの派閥対立・分断化）',
    phase: 3,
    importance: 3,
    importanceReason: 'アベンジャーズが２つに分裂。スパイダーマン、ブラックパンサーがMCU初参戦する実質「アベンジャーズ2.5」と言える重要作。',
    synopsis: '一般市民の犠牲を防ぐため、ヒーローを国連管理下に置く「ソコヴィア協定」が提出される。その署名をめぐり「賛成（トニー）」と「反対（スティーブ）」にヒーローたちの意見が真っ二つに分かれる。',
    directorOrCreator: 'アンソニー＆ジョー・ルッソ',
    durationOrEpisodes: '2時間27分',
    officialUrl: 'https://marvel.disney.co.jp/movie/civilwar-ca',
    explanationUrlQuery: 'シビルウォー キャプテンアメリカ ネタバレ 考察 バッキー'
  },
  {
    id: 'black_widow',
    titleJa: 'ブラック・ウィドウ',
    titleEn: 'Black Widow',
    type: 'movie',
    releaseDate: '2021-07-09', // Released early Phase 4, but chronologically placed in Phase 3
    releaseOrder: 24,
    chronoOrder: 16,
    chronoSetting: '2016年（シビル・ウォーの直後）',
    phase: 4,
    importance: 2,
    importanceReason: 'ナターシャ・ロマノフの失われた過去と、妹分エレーナとの出会い。アベンジャーズに合流する前の逃亡生活の裏側。',
    synopsis: 'シビル・ウォー直後、逃亡身のナターシャはかつて自身を暗殺者に育て上げた「レッドルーム」の陰謀を感知。自身の家族（妹エレーナ、母、父）と再会し、隠された悪を断ち切る戦いに挑む。',
    directorOrCreator: 'ケイト・ショートランド',
    durationOrEpisodes: '2時間14分',
    officialUrl: 'https://marvel.disney.co.jp/movie/blackwidow',
    explanationUrlQuery: 'ブラックウィドウ ネタバレ 考察 エンドロールの意味'
  },
  {
    id: 'black_panther',
    titleJa: 'ブラックパンサー',
    titleEn: 'Black Panther',
    type: 'movie',
    releaseDate: '2018-02-16',
    releaseOrder: 18,
    chronoOrder: 17,
    chronoSetting: '2016年 一週間後（シビル・ウォー直後）',
    phase: 3,
    importance: 3,
    importanceReason: 'アカデミー賞最優秀作品賞ノミネート。超ハイテク国家「ワカンダ」の王、ティ・チャラの即位。ヴィランのキルモンガーも屈指の人気。',
    synopsis: '若き国王ティ・チャラは、超文明国ワカンダの秘密を守りながら謎の襲撃者キルモンガーと戦う。王としての覚悟と、鎖国か開国かの重い決断を迫られる。',
    directorOrCreator: 'ライアン・クーグラー',
    durationOrEpisodes: '2時間14分',
    officialUrl: 'https://marvel.disney.co.jp/movie/blackpanther',
    explanationUrlQuery: 'ブラックパンサー ネタバレ 考察 ワカンダテクノロジー'
  },
  {
    id: 'spider_man_hc',
    titleJa: 'スパイダーマン:ホームカミング',
    titleEn: 'Spider-Man: Homecoming',
    type: 'movie',
    releaseDate: '2017-07-07',
    releaseOrder: 16,
    chronoOrder: 18,
    chronoSetting: '2016年 秋（シビル・ウォーの数ヶ月後）',
    phase: 3,
    importance: 2,
    importanceReason: 'ピーター・パーカー（スパイダーマン）の本格的な単独戦闘開始。トニー・スタークが師匠（メンター）として登場。',
    synopsis: '空港対戦を終えてハイテンションなピーター。トニー・スタークから預かった最新スーツでヒーローを名乗るが、「若すぎる」として重要な仕事を任せてもらえない中、危険な武器密売チームと接触する。',
    directorOrCreator: 'ジョン・ワッツ',
    durationOrEpisodes: '2時間13分',
    officialUrl: 'https://marvel.disney.co.jp/movie/spiderman-homecoming',
    explanationUrlQuery: 'スパイダーマン ホームカミング ネタバレ 考察 バルチャー'
  },
  {
    id: 'doctor_strange',
    titleJa: 'ドクター・ストレンジ',
    titleEn: 'Doctor Strange',
    type: 'movie',
    releaseDate: '2016-11-04',
    releaseOrder: 14,
    chronoOrder: 19,
    chronoSetting: '2016年 - 2017年（トニーたちの戦いの裏側）',
    phase: 3,
    importance: 3,
    importanceReason: '魔術（マルチバース）の概念を導入する。タイム・ストーン「アガモットの目」が登場する。',
    synopsis: '傲慢な天才外科医ストレンジは両手に大怪我を負い、治療の手がかりを求めカトマンズの聖地へ。そこで魔術を体得した彼は、多次元世界の邪悪な存在から地球を暗暗から救うため、魔術師として立ち上がる。',
    directorOrCreator: 'スコット・デリクソン',
    durationOrEpisodes: '1時間55分',
    officialUrl: 'https://marvel.disney.co.jp/movie/dr-strange',
    explanationUrlQuery: 'ドクターストレンジ1 ネタバレ 考察 タイムストーン'
  },
  {
    id: 'thor_ragnarok',
    titleJa: 'マイティ・ソー バトルロイヤル',
    titleEn: 'Thor: Ragnarok',
    type: 'movie',
    releaseDate: '2017-11-03',
    releaseOrder: 17,
    chronoOrder: 20,
    chronoSetting: '2017年（インフィニティ・ウォー直前の宇宙）',
    phase: 3,
    importance: 3,
    importanceReason: 'ソーのパワーアップ、アスガルドの最期、宇宙にいたハルクの合流と、そのままインフィニティ・ウォーのオープニングに繋がる極めて重要な一作。',
    synopsis: '幽閉から解き放たれ最強最悪の敵となった姉・死の女神ヘラに挑むソー。ムジョルニア（ハンマー）を破壊され、辺境の闘技場で仲間を集めて、崩壊の一歩手前にあるアスガルドを奪還すべく決死の脱出を図る。',
    directorOrCreator: 'タイカ・ワイティティ',
    durationOrEpisodes: '2時間10分',
    officialUrl: 'https://marvel.disney.co.jp/movie/thor-br',
    explanationUrlQuery: 'マイティソー バトルロイヤル ラグナロク ネタバレ 考察 ポストクレジット'
  },
  {
    id: 'ant_man_and_the_wasp',
    titleJa: 'アントマン&ワスプ',
    titleEn: 'Ant-Man and the Wasp',
    type: 'movie',
    releaseDate: '2018-07-06',
    releaseOrder: 20,
    chronoOrder: 21,
    chronoSetting: '2018年（インフィニティ・ウォー直前の地上）',
    phase: 3,
    importance: 3,
    importanceReason: '女性ヒーロー「ワスプ」の参戦。エンドゲームを解決するための鍵となるシーンがラストに。',
    synopsis: 'シビル・ウォーに無断参加したことで自宅軟禁中のスコット。ピム親娘から協力を要請され、相棒ワスプと共に量子世界に囚われた初代ワスプを救い出す計画に奔走するが、障害物幽霊「ゴースト」が現れる。',
    directorOrCreator: 'ペイトン・リード',
    durationOrEpisodes: '1時間58分',
    officialUrl: 'https://marvel.disney.co.jp/movie/antman-wasp',
    explanationUrlQuery: 'アントマン アンド ワスプ ネタバレ 考察 ポストクレジット 消滅'
  },
  {
    id: 'avengers_iw',
    titleJa: 'アベンジャーズ/インフィニティ・ウォー',
    titleEn: 'Avengers: Infinity War',
    type: 'movie',
    releaseDate: '2018-04-27',
    releaseOrder: 19,
    chronoOrder: 22,
    chronoSetting: '2018年（宇宙・地球規模のサノス襲撃）',
    phase: 3,
    importance: 3,
    importanceReason: 'MCU最大のボス「サノス」がついに全貌を現し、ヒーローたちと最大規模の全面対決を展開する、エンドゲームと並ぶ超大作。',
    synopsis: '6つのインフィニティ・ストーンで全宇宙の生命を半分に減らそうとするサノス。アベンジャーズ、ガーディアンズ・オブ・ギャラクシーらが地球と宇宙の両方で死闘を繰り広げるが、予想外の結末が待っていた。',
    directorOrCreator: 'アンソニー＆ジョー・ルッソ',
    durationOrEpisodes: '2時間29分',
    officialUrl: 'https://marvel.disney.co.jp/movie/avengers-iw',
    explanationUrlQuery: 'アベンジャーズ インフィニティウォー ネタバレ 考察 ラスト衝撃解釈'
  },
  {
    id: 'captain_marvel',
    titleJa: 'キャプテン・マーベル',
    titleEn: 'Captain Marvel',
    type: 'movie',
    releaseDate: '2019-03-08',
    releaseOrder: 21,
    chronoOrder: 2,
    chronoSetting: '1995年（アベンジャーズ誕生前夜）',
    phase: 3,
    importance: 3,
    importanceReason: '最強戦士キャプテン・マーベルのオリジン。若き日のニック・フューリーやS.H.I.E.L.D.の初期に深く関わる、時系列上2番目の作品。',
    synopsis: '記憶を失った規格外のパワーを持つ女性戦士キャロル・ダンヴァース。地球に落下した彼女は、まだ若く眼帯を付けていないニック・フューリーと出会い、自身の出生の秘密に隠されたスクラル人とクリー人の戦争に立ち向かう。',
    directorOrCreator: 'アンナ・ボーデン＆ライアン・フレック',
    durationOrEpisodes: '2時間4分',
    officialUrl: 'https://marvel.disney.co.jp/movie/captain-marvel',
    explanationUrlQuery: 'キャプテンマーベル ネタバレ 考察 四次元キューブ 猫'
  },
  {
    id: 'avengers_eg',
    titleJa: 'アベンジャーズ/エンドゲーム',
    titleEn: 'Avengers: Endgame',
    type: 'movie',
    releaseDate: '2019-04-26',
    releaseOrder: 22,
    chronoOrder: 23,
    chronoSetting: '2018年 - 2023年（サノスとの最終決戦とタイム強奪）',
    phase: 3,
    importance: 3,
    importanceReason: 'インフィニティ・サーガ（フェーズ1〜3）の壮大なフィナーレにして映画史に残る傑作。絶対に外せないMCU鑑賞の最大のクライマックス。',
    synopsis: 'サノスによって生命の半分が消滅した地獄から5年。量子世界から帰還したアントマンのアイデアにより、残されたアベンジャーズは再び歴史を取り戻すためリスクを冒して「時の強奪戦」に挑み、サノスを打倒する最終決戦へ臨む。',
    directorOrCreator: 'アンソニー＆ジョー・ルッソ',
    durationOrEpisodes: '3時間1分',
    officialUrl: 'https://marvel.disney.co.jp/movie/avengers-endgame',
    explanationUrlQuery: 'アベンジャーズ エンドゲーム ネタバレ 考察 完璧伏線回収'
  },
  {
    id: 'spider_man_ffh',
    titleJa: 'スパイダーマン:ファー・フロム・ホーム',
    titleEn: 'Spider-Man: Far From Home',
    type: 'movie',
    releaseDate: '2019-07-02',
    releaseOrder: 23,
    chronoOrder: 27,
    chronoSetting: '2024年 夏（エンドゲームから8ヶ月後）',
    phase: 3,
    importance: 3,
    importanceReason: 'フェーズ3（インフィニティ・サーガ）のエピローグ。トニー・スタークの後継者を巡り、「ミステリオ」と死闘を演じる。',
    synopsis: 'トニー亡き世界で、ヒーローのプレッシャーに苦しむピーター。夏休みとしてヨーロッパ旅行に出発するが、行く先々でエレメンタルズ（元素モンスター）が襲来。謎の新ヒーロー「ミステリオ」と協力することに。',
    directorOrCreator: 'ジョン・ワッツ',
    durationOrEpisodes: '2時間9分',
    officialUrl: 'https://marvel.disney.co.jp/movie/spiderman-farfromhome',
    explanationUrlQuery: 'スパイダーマン ファーフロムホーム ネタバレ 考察 ラストネタバレ'
  },

  // --- PHASE 4 ---
  {
    id: 'wandavision',
    titleJa: 'ワンダヴィジョン',
    titleEn: 'WandaVision',
    type: 'drama',
    releaseDate: '2021-01-15',
    releaseOrder: 25,
    chronoOrder: 25,
    chronoSetting: '2023年（エンドゲーム後、わずか3週間後）',
    phase: 4,
    importance: 3,
    importanceReason: '初のディズニープラス独占ドラマ。ドクター・ストレンジMoMの展開への密接な導入部であり、ワンダの暴走と悲しみを深く描く。',
    synopsis: '幸せな新婚生活を送るはずがないヴィジョンとワンダ。しかしアメリカ流レトロなシットコム（コメディ）の世界で奇妙な生活が続く中、背後に何者かの欺瞞を感じ始め、舞台は劇的に変貌していく。',
    directorOrCreator: 'ジャック・シェイファー',
    durationOrEpisodes: '全9話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/wandavision',
    explanationUrlQuery: 'ワンダヴィジョン ネタバレ 考察 結末解説'
  },
  {
    id: 'falcon_winter_soldier',
    titleJa: 'ファルコン&ウィンター・ソルジャー',
    titleEn: 'The Falcon and the Winter Soldier',
    type: 'drama',
    releaseDate: '2021-03-19',
    releaseOrder: 26,
    chronoOrder: 26,
    chronoSetting: '2024年（エンドゲームの6ヶ月後）',
    phase: 4,
    importance: 3,
    importanceReason: '2代目キャプテン・アメリカ誕生を描く。スティーブから盾を受け継いだサムの葛藤と黒人のアイデンティティを描いた本格ドラマ。',
    synopsis: 'キャプテン・アメリカが去った後、サムは彼の遺志を継ぐことに懐疑的だった。バッキーと共に世界に暗躍する過激派集団フラッグ・スマッシャーズを追いながら、真のキャプテンとは何かという問いに向き合う。',
    directorOrCreator: 'カリ・スコグランド',
    durationOrEpisodes: '全6話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/falcon-winter-soldier',
    explanationUrlQuery: 'ファルコンアンドウィンターソルジャー ネタバレ 考察 結末'
  },
  {
    id: 'loki_s1',
    titleJa: 'ロキ シーズン1',
    titleEn: 'Loki Season 1',
    type: 'drama',
    releaseDate: '2021-06-09',
    releaseOrder: 27,
    chronoOrder: 24,
    chronoSetting: '時の枠外 (12年のアベンジャーズ直後から分岐)',
    phase: 4,
    importance: 3,
    importanceReason: 'MCU「マルチバース・サーガ」の最大設定書。マルチバースの破綻と時間軸管理組織TVA、そしてサノス以降のヴィラン「征服者カーン」の紹介。',
    synopsis: 'ニューヨーク決戦（エンドゲーム中）で4次元キューブを奪って逃走した罰当たりロキ。時間軸を乱した罪で時間変異取締局（TVA）に捕まり、タイムラインを修復する代わりにさらなる「世界の真実」と対峙する。',
    directorOrCreator: 'マイケル・ウォルドロン',
    durationOrEpisodes: '全6話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/loki',
    explanationUrlQuery: 'ロキ ドラマ ネタバレ 考察 タイムライン'
  },
  {
    id: 'shang_chi',
    titleJa: 'シャン・チー/テン・リングスの伝説',
    titleEn: 'Shang-Chi and the Legend of the Ten Rings',
    type: 'movie',
    releaseDate: '2021-09-03',
    releaseOrder: 28,
    chronoOrder: 28,
    chronoSetting: '2024年（マカオやサンフランシスコ）',
    phase: 4,
    importance: 2,
    importanceReason: '新たな武術系アジアン・ヒーロー「シャン・チー」の紹介、アイアンマン3でニセモノが登場した悪党「テン・リングス」の正体が明らかに。',
    synopsis: 'ホテル従業員として目立たず平穏な生活を送るシャン・チー。だがかつて父によって暗殺者として育てられ逃亡した過去があった。父が率いる暗黒の力「テン・リングス」に呼び戻され実家で骨肉の争いが始まる。',
    directorOrCreator: 'デスティン・ダニエル・クレットン',
    durationOrEpisodes: '2時間12分',
    officialUrl: 'https://marvel.disney.co.jp/movie/shang-chi',
    explanationUrlQuery: 'シャンチー テンリングスの伝説 ネタバレ 考察 父親の名前'
  },
  {
    id: 'eternals',
    titleJa: 'エターナルズ',
    titleEn: 'Eternals',
    type: 'movie',
    releaseDate: '2021-11-05',
    releaseOrder: 29,
    chronoOrder: 29,
    chronoSetting: '2024年（全人類史の神話を渡る数千年、現在）',
    phase: 4,
    importance: 1,
    importanceReason: '人類を太古から陰ながら保護し続けてきた神々のごとき超生命体「エターナルズ」を描き、MCUの神話的な世界観を極限まで引き上げる。',
    synopsis: '地球外生命を脅かす捕食犬ディヴィアンツを討伐するために何千年も昔から地球に降臨していた10人の戦士エターナルズ。ディヴィアンツが現代に復讐しに蘇ったため再び召集され、地球滅亡を促す巨大な生命創造「出現（エマージェンス）」を目撃し苦渋の決断を下す。',
    directorOrCreator: 'クロエ・ジャオ',
    durationOrEpisodes: '2時間36分',
    officialUrl: 'https://marvel.disney.co.jp/movie/eternals',
    explanationUrlQuery: 'エターナルズ ネタバレ 考察 セレスティアルズの意味'
  },
  {
    id: 'hawkeye',
    titleJa: 'ホークアイ',
    titleEn: 'Hawkeye',
    type: 'drama',
    releaseDate: '2021-11-24',
    releaseOrder: 30,
    chronoOrder: 30,
    chronoSetting: '2024年 クリスマス（エンドゲームの1年後）',
    phase: 4,
    importance: 2,
    importanceReason: '若き射手ケイト・ビショップの育成。ブラック・ウィドウの妹エレーナや、かつてのNetflix版ヴィラン「キングピン」が交差する重要事件。',
    synopsis: 'アベンジャーズとしてお役目を終えて平穏なクリスマスを家族と過ごすホークアイことクリント。だが、自身が過激な暗殺者ローニンだった時代のスーツをケイト・ビショップが勝手に着て暗黒街に現れたため、嫌々ながら彼女と共に事件を収束させる旅に出る。',
    directorOrCreator: 'ジョナサン・イグラ',
    durationOrEpisodes: '全6話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/hawkeye',
    explanationUrlQuery: 'ホークアイ ドラマ ネタバレ 考察 ケイト ロニン'
  },
  {
    id: 'spider_man_nwh',
    titleJa: 'スパイダーマン:ノー・ウェイ・ホーム',
    titleEn: 'Spider-Man: No Way Home',
    type: 'movie',
    releaseDate: '2021-12-17',
    releaseOrder: 31,
    chronoOrder: 31,
    chronoSetting: '2024年 秋冬（前作FFHおよびホークアイと重なる時期）',
    phase: 4,
    importance: 3,
    importanceReason: 'スパイダーマン実写映画史を全て包摂するMCU最大の奇跡。マルチバースの本格的事故に加え、トビー・マグワイア、アンドリュー・ガーフィールドも登場。',
    synopsis: 'ミステリオの暴露で正体が世間にバレ、恋人や親友の進学まで阻害されて困惑したピーターはドクター・ストレンジの魔術で人々の記憶を消そうとしミス。そこへ、他ユニバースからお馴染みの歴代ヴィラン（ドック・オック、グリーン・ゴブリン、エレクトロら）が召喚されてしまう。',
    directorOrCreator: 'ジョン・ワッツ',
    durationOrEpisodes: '2時間28分',
    officialUrl: 'https://marvel.disney.co.jp/movie/spiderman-nwh',
    explanationUrlQuery: 'スパイダーマン ノーウェイホーム ネタバレ 考察 歴代合流 ラスト'
  },
  {
    id: 'moon_knight',
    titleJa: 'ムーンナイト',
    titleEn: 'Moon Knight',
    type: 'drama',
    releaseDate: '2022-03-30',
    releaseOrder: 32,
    chronoOrder: 33,
    chronoSetting: '2025年（イギリス・エジプトなど独立ストーリー）',
    phase: 4,
    importance: 1,
    importanceReason: '他のMCUと比較的関連の少ない、完全新規のアクション怪作。エジプト神話の神コシューと契約した二重人格のダークヒーロー。',
    synopsis: '心優しい大人しい博物館員スティーヴンはある日突然、多重人格者でもう一方の暴力的な人格「マーク」がエジプトの暗殺神の代理人として戦っていることを知る。おかしな行動障害に苛まれながら神威の力を身に纏い、カルト教団と神々の遺産を巡って世界の裏で闘争する。',
    directorOrCreator: 'ジェレミー・スレイター',
    durationOrEpisodes: '全6話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/moonknight',
    explanationUrlQuery: 'ムーンナイト ネタバレ 考察 二重人格 結末'
  },
  {
    id: 'doctor_strange_mom',
    titleJa: 'ドクター・ストレンジ/マルチバース・オブ・マッドネス',
    titleEn: 'Doctor Strange in the Multiverse of Madness',
    type: 'movie',
    releaseDate: '2022-05-06',
    releaseOrder: 33,
    chronoOrder: 32,
    chronoSetting: '2025年（ワンダビジョンと直結、NWHの直後）',
    phase: 4,
    importance: 3,
    importanceReason: '本格的に他並行世界（マルチバース）の旅を描く。ワンダが強大な敵役として参戦。プロフェッサーXなどファン歓喜のカメオ出演の嵐。',
    synopsis: 'マルチバースを自在に渡る能力を持つ少女アメリカ・チャベスが巨大怪物に襲われている現場を救うストレンジ。だが彼女の命とパワーをつけ狙っているのが、ワンダビジョン後に狂気へと足を踏み入れたスカーレット・ウィッチ（ワンダ）本人であると知り、ストレンジは宇宙を跨ぐ逃亡・防衛戦へ踏み出す。',
    directorOrCreator: 'サム・ライミ',
    durationOrEpisodes: '2時間6分',
    officialUrl: 'https://marvel.disney.co.jp/movie/dr-strange-mom',
    explanationUrlQuery: 'ドクターストレンジ マルチバースオブマッドネス ネタバレ 考察 イルミナティ'
  },
  {
    id: 'ms_marvel',
    titleJa: 'ミズ・マーベル',
    titleEn: 'Ms. Marvel',
    type: 'drama',
    releaseDate: '2022-06-08',
    releaseOrder: 34,
    chronoOrder: 34,
    chronoSetting: '2025年（マーベルズに直接つながる前日譚）',
    phase: 4,
    importance: 2,
    importanceReason: '映画「マーベルズ」の主人公三人組の一柱、カマラ・カーンのオリジン。ミュータント（X-MEN）要素の布石。',
    synopsis: 'キャプテン・マーベルの超大ファンの女子高生カマラ。祖母の不思議な腕輪（バングル）をはめたことで光を具現化する超能力を覚醒させる。彼女はジャージ姿の新米ヒーロー「ミズ・マーベル」として町の安全を護り、自身のルーツと謎の闇組織に狙われ始める。',
    directorOrCreator: 'ビシャ・K・アリ',
    durationOrEpisodes: '全6話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/ms-marvel',
    explanationUrlQuery: 'ミズマーベル ネタバレ 考察 腕輪の意味 ラスト'
  },
  {
    id: 'thor_love_and_thunder',
    titleJa: 'ソー:ラブ&サンダー',
    titleEn: 'Thor: Love and Thunder',
    type: 'movie',
    releaseDate: '2022-07-08',
    releaseOrder: 35,
    chronoOrder: 35,
    chronoSetting: '2025年（宇宙でのガーディアンズとの共闘〜神殺し）',
    phase: 4,
    importance: 2,
    importanceReason: '元恋人ジェーンが「マイティ・ソー」に変身。ガン闘病中の彼女との最後の愛、そして全神々を抹殺せんとするゴアの討伐。',
    synopsis: '悟りを開いて引退宣言したソー。だが神殺しゴアが宇宙の全ての神々を根絶しようとアスガルドの新たな拠点（ニュー・アスガルド）を急襲、さらにソーと同じ力を宿した輝くジェーンが戦いの渦中に姿を現し、神々の王ゼウスに会いに行く。',
    directorOrCreator: 'タイカ・ワイティティ',
    durationOrEpisodes: '119分',
    officialUrl: 'https://marvel.disney.co.jp/movie/thor-love-and-thunder',
    explanationUrlQuery: 'ソー ラブアンドサンダー ネタバレ 考察 ゴア 結末の娘'
  },
  {
    id: 'she_hulk',
    titleJa: 'シー・ハルク:ザ・アトーニー',
    titleEn: 'She-Hulk: Attorney at Law',
    type: 'drama',
    releaseDate: '2022-08-18',
    releaseOrder: 36,
    chronoOrder: 36,
    chronoSetting: '2025年（オマージュコメディ、ハルクの紹介）',
    phase: 4,
    importance: 1,
    importanceReason: '第4の壁を突破する（視聴者に直接語りかける）お笑い系法廷ドラマ。デアデビルの参戦。',
    synopsis: '普通の弁護士ジェニファーは、従兄のブルース・バナーのハルク血液が偶発的に傷口に入りグリーン巨人パワーを継承。ヒーロー法の専門部門リーダーを担当させられる中、変人の超人クライアントたちの難題を、ギャグを交えて愉快に裁判にかける。',
    directorOrCreator: 'ジェシカ・ガオ',
    durationOrEpisodes: '全9話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/she-hulk',
    explanationUrlQuery: 'シーハルク ネタバレ 考察 デアデビル 結末メタ'
  },
  {
    id: 'black_panther_wf',
    titleJa: 'ブラックパンサー/ワカンダ・フォーエバー',
    titleEn: 'Black Panther: Wakanda Forever',
    type: 'movie',
    releaseDate: '2022-11-11',
    releaseOrder: 37,
    chronoOrder: 37,
    chronoSetting: '2025年（ティ・チャラの死去、深海との全面戦争）',
    phase: 4,
    importance: 3,
    importanceReason: '主役チャドウィック・ボーズマンの他界という現実を物語に重ね、ティ・チャラ亡き後のワカンダに迫る他文明アトランティス（ネイモア）との死闘、妹シュリの苦悩と覚悟。',
    synopsis: '国王ティ・チャラが不治の病で逝去。哀しみに沈むワカンダに対し、ヴィブラニウムを狙う世界からの脅威と、深海に潜むタロカン帝国王ネイモアの最後通告が突きつけられる。若きシュリは自ら戦士となるべきかの答えを探す。',
    directorOrCreator: 'ライアン・クーグラー',
    durationOrEpisodes: '2時間41分',
    officialUrl: 'https://marvel.disney.co.jp/movie/blackpanther-wf',
    explanationUrlQuery: 'ブラックパンサー ワカンダフォーエバー ネタバレ 考察 新生ブラックパンサー'
  },

  // --- PHASE 5 ---
  {
    id: 'ant_man_q',
    titleJa: 'アントマン&ワスプ:クアントマニア',
    titleEn: 'Ant-Man and the Wasp: Quantumania',
    type: 'movie',
    releaseDate: '2023-02-17',
    releaseOrder: 38,
    chronoOrder: 38,
    chronoSetting: '2025-2026年（量子世界の最深部、フェーズ5開幕）',
    phase: 5,
    importance: 3,
    importanceReason: 'フェーズ5の開幕を飾る超SF巨編。最大の強敵「征服者カーン」との直接対決が主軸となる。',
    synopsis: 'スコットの愛娘キャシーが作った量子世界の探索機が突然暴走。ピム博士や妻ワスプの家族全員ごと、1cmのその何億倍も小さい「量子世界」の深奥に吸い込まれてしまう。一同はそこで、時間を完全に支配する征服者カーンに遭遇する。',
    directorOrCreator: 'ペイトン・リード',
    durationOrEpisodes: '2時間5分',
    officialUrl: 'https://marvel.disney.co.jp/movie/antman-wasp-qm',
    explanationUrlQuery: 'アントマン クアントマニア ネタバレ 考察 征服者カーン'
  },
  {
    id: 'guardians_of_the_galaxy_vol3',
    titleJa: 'ガーディアンズ・オブ・ギャラクシー:VOLUME 3',
    titleEn: 'Guardians of the Galaxy Vol. 3',
    type: 'movie',
    releaseDate: '2023-05-05',
    releaseOrder: 39,
    chronoOrder: 39,
    chronoSetting: '2026年（ロケットの生命危機と最古の狂気、完結編）',
    phase: 5,
    importance: 3,
    importanceReason: 'ジェームズ・ガンによるスペースヒーロー「ガーディアンズ」神話の究極のフィナーレ。ロケットの凄惨な過去が焦点となる大傑作。',
    synopsis: '凶暴アライグマ・ロケットが謎の強敵アダム・ウォーロックの奇襲で生命維持困難に。彼の心臓のパスコード解除をするため、コズミック遺伝子創造主「ハイ・エボリューショナリー」の地球風要塞へ潜入する大救出決闘。',
    directorOrCreator: 'ジェームズ・ガン',
    durationOrEpisodes: '2時間30分',
    officialUrl: 'https://marvel.disney.co.jp/movie/gog-v3',
    explanationUrlQuery: 'ガーディアンズオブギャラクシー3 ネタバレ 考察 結末 その後'
  },
  {
    id: 'secret_invasion',
    titleJa: 'シークレット・インベージョン',
    titleEn: 'Secret Invasion',
    type: 'drama',
    releaseDate: '2023-06-21',
    releaseOrder: 40,
    chronoOrder: 40,
    chronoSetting: '2026年（地球上の偽装サスペンス）',
    phase: 5,
    importance: 2,
    importanceReason: 'スパイサスペンス。ニック・フューリーの帰還と、ヒーローたちがスクラル人に成り代わっているのではないかという混沌。',
    synopsis: '何年も消息不明だったニック・フューリーが、他人の姿を精巧に擬態できる宇宙人スクラルが、地球国家の要職や権力者を密かに乗っ取ろうとしている陰謀「静かなる侵略」を防ぐために独り奮闘する。',
    directorOrCreator: 'カイル・ブラッドストリート',
    durationOrEpisodes: '全6話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/secret-invasion',
    explanationUrlQuery: 'シークレットインベージョン ネタバレ 考察 ラストの意味'
  },
  {
    id: 'loki_s2',
    titleJa: 'ロキ シーズン2',
    titleEn: 'Loki Season 2',
    type: 'drama',
    releaseDate: '2023-10-05',
    releaseOrder: 41,
    chronoOrder: 42,
    chronoSetting: '時の枠外（無限のマルチバース崩壊の阻止）',
    phase: 5,
    importance: 3,
    importanceReason: 'ヴィランであったロキの最終到達点。時間軸（タイムスリップ設定）とMCU「大いなるマルチバース樹形」の覚醒。絶対見るべき大絶賛ドラマ。',
    synopsis: '崩壊を始める全マルチバース・タイムライン。ロキは時間が制御不能になって、TVAから消滅しそうになるお馴染みの仲間たちを、タイム・スリップ能力を使って過去・現在を巡って再編、最後のとてつもない自己犠牲に臨む。',
    directorOrCreator: 'ジャスティン・ベンソン＆アーロン・ムーアヘッド',
    durationOrEpisodes: '全6話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/loki-season2',
    explanationUrlQuery: 'ロキ シーズン2 ネタバレ 考察 ラスト玉座の意味'
  },
  {
    id: 'the_marvels',
    titleJa: 'マーベルズ',
    titleEn: 'The Marvels',
    type: 'movie',
    releaseDate: '2023-11-10',
    releaseOrder: 42,
    chronoOrder: 41,
    chronoSetting: '2026年（キャロル、モニカ、カマラの光の接続）',
    phase: 5,
    importance: 2,
    importanceReason: 'キャプテン・マーベル、モニカ、ミズ・マーベルの３人の位置が「能力の使用」で瞬時に入れ替わる。X-MENへの新たな接続。',
    synopsis: 'クリー帝国の新たな女指導者ダー・ベンが、衰退する惑星のために光のバングルを用いて特大超空間ホールを開放。その特異点爆発の影響で、キャプテン・マーベル、ワンダ愛娘モニカ、ミズ・マーベルの３人が、力を使う度に入れ替わる奇妙なバグとなり、３人一緒の戦闘を組み立てる。',
    directorOrCreator: 'ニア・ダコスタ',
    durationOrEpisodes: '105分',
    officialUrl: 'https://marvel.disney.co.jp/movie/the-marvels',
    explanationUrlQuery: 'マーベルズ ネタバレ 考察 XMEN ビースト ポストクレジット'
  },
  {
    id: 'deadpool_and_wolverine',
    titleJa: 'デッドプール&ウルヴァリン',
    titleEn: 'Deadpool & Wolverine',
    type: 'movie',
    releaseDate: '2024-07-26',
    releaseOrder: 43,
    chronoOrder: 44,
    chronoSetting: '2024年-2026年（別バース・TVA・虚無空間ヴォイド）',
    phase: 5,
    importance: 3,
    importanceReason: 'Fox版マーベル（X-MENなど）をMCUに合流させる、デッドプール史上最も破天荒かつメタ視点で語られる爆笑アクション大作。マルチバース救済。',
    synopsis: 'ウェイド（デッドプール）の平和な日常の宇宙は、「大いなる錨（アンカー）」であったウルヴァリンを失ったことで自己崩壊の危機に陥る。それを救うため、彼はTVAから奪った時空間移動機器で別宇宙の「やる気のないウルヴァリン」を拉致して、荒野ボイドを彷徨い救済を狙う。',
    directorOrCreator: 'ショーン・レヴィ',
    durationOrEpisodes: '2時間8分',
    officialUrl: 'https://marvel.disney.co.jp/movie/deadpool-and-wolverine',
    explanationUrlQuery: 'デッドプールアンドウルヴァリン ネタバレ 考察 カメオ出演 解説'
  },
  {
    id: 'agatha_all_along',
    titleJa: 'アガサ・オール・アロング',
    titleEn: 'Agatha All Along',
    type: 'drama',
    releaseDate: '2024-09-18',
    releaseOrder: 44,
    chronoOrder: 45,
    chronoSetting: '2026年（「魔女の道」を探求するワンダビジョンの後日譚）',
    phase: 5,
    importance: 2,
    importanceReason: 'ワンダヴィジョンの直接的な実質続編。魔術、特にゴス・魔女・スピリチュアル世界と、ワンダの息子「ビリー（ウィッカン）」の探求。',
    synopsis: 'ワンダに呪縛され田舎町の警察官を夢想していたアガサ。怪しい少年の協力で呪いを解除されるが魔力を失っていた。失った力を最奥で手に入れられる伝説の地「魔女の道」を攻略すべく、風変わりな魔女仲間を集め危険な試練の道を進んでいく。',
    directorOrCreator: 'ジャック・シェイファー',
    durationOrEpisodes: '全9話（ディズニープラス）',
    officialUrl: 'https://marvel.disney.co.jp/movie/agatha-all-along',
    explanationUrlQuery: 'アガサオールアロング ネタバレ 考察 ティーン 正体 結末'
  },
  {
    id: 'what_if_s3',
    titleJa: 'ホワット・イフ...？ シーズン3',
    titleEn: 'What If...? Season 3',
    type: 'drama',
    releaseDate: '2024-12-22',
    releaseOrder: 45,
    chronoOrder: 46,
    chronoSetting: 'マルチバース（ウォッチャーが観測する無限の可能性）',
    phase: 5,
    importance: 1,
    importanceReason: 'マルチバースを舞台に、もしもの物語を描くアニメシリーズ最終シーズン。設定の裏付けやキャラクターの別側面を描く。',
    synopsis: 'ウォッチャーが再び、無限に広がるマルチバースの様々な「もしも」の物語を案内する。おなじみのヒーローたちが奇想天外な運命を辿る、MCUマルチバース最後の短編アニメ集。',
    directorOrCreator: 'ブライアン・アンドリュース',
    durationOrEpisodes: '全8話',
    officialUrl: 'https://marvel.disney.co.jp/movie/what-if',
    explanationUrlQuery: 'ホワットイフ シーズン3 ネタバレ 考察'
  },
  {
    id: 'captain_america_bnw',
    titleJa: 'キャプテン・アメリカ：ブレイブ・ニュー・ワールド',
    titleEn: 'Captain America: Brave New World',
    type: 'movie',
    releaseDate: '2025-02-14',
    releaseOrder: 46,
    chronoOrder: 47,
    chronoSetting: '2026年（サムがキャプテン・アメリカを引き継いだ後の国際情勢）',
    phase: 5,
    importance: 3,
    importanceReason: 'サム・ウィルソンが初の単独主役としてキャプテン・アメリカを襲名した映画。サディアス・ロス大統領（レッドハルク）との対立が描かれる。',
    synopsis: 'キャプテン・アメリカの盾を正式に継承したサム。大統領となったサディアス・ロスとの会談後、全世界を揺るがす国際的な軍事陰謀に巻き込まれ、新たな仲間と共に陰の巨大な悪に挑む。',
    directorOrCreator: 'ジュリアス・オナ',
    durationOrEpisodes: '118分',
    officialUrl: 'https://marvel.disney.co.jp/movie/captain-america-bnw',
    explanationUrlQuery: 'キャプテンアメリカ ブレイブニューワールド ネタバレ 考察 レッドハルク'
  },
  {
    id: 'daredevil_born_again',
    titleJa: 'デアデビル：ボーン・アゲイン',
    titleEn: 'Daredevil: Born Again',
    type: 'drama',
    releaseDate: '2025-03-04',
    releaseOrder: 47,
    chronoOrder: 48,
    chronoSetting: '2026年（ニューヨークの裏社会、キングピンの市政支配）',
    phase: 5,
    importance: 2,
    importanceReason: 'Netflix版から正式にMCUに完全統合されたデアデビルの最新ドラマ。キングピンとの宿命の法廷・肉体バトル。',
    synopsis: '盲目の弁護士マット・マードックは、夜は「デアデビル」として地獄のキッチンで法で裁けぬ悪と戦う。ニューヨーク市長となった宿敵キングピンが、法と権力を悪用しヒーローを排除しようと動き出す。',
    directorOrCreator: 'ダリオ・スカルダペイン',
    durationOrEpisodes: '全9話',
    officialUrl: 'https://marvel.disney.co.jp/movie/daredevil-born-again',
    explanationUrlQuery: 'デアデビル ボーンアゲイン ネタバレ 考察 キングピン'
  },
  {
    id: 'thunderbolts',
    titleJa: 'サンダーボルツ*',
    titleEn: 'Thunderbolts*',
    type: 'movie',
    releaseDate: '2025-04-30',
    releaseOrder: 48,
    chronoOrder: 49,
    chronoSetting: '2026年（政府の裏仕事、クセ者ぞろいのアンチヒーロー集団）',
    phase: 5,
    importance: 3,
    importanceReason: 'これまでの作品で暗躍や苦悩してきたヴィラン、アンチヒーローたちが非公式にスクワッドを結成する超注目作。',
    synopsis: 'エレーナ（ブラック・ウィドウの妹）、バッキー（ウィンター・ソルジャー）、USエージェントら、過去に心に傷を抱えた「はみ出し者」たちが、ヴァレンティーナの手によって不本意ながらも決死の作戦チーム「サンダーボルツ」を結成させられる。',
    directorOrCreator: 'ジェイク・シュライアー',
    durationOrEpisodes: '2時間12分',
    officialUrl: 'https://marvel.disney.co.jp/movie/thunderbolts',
    explanationUrlQuery: 'サンダーボルツ アスタリスク ネタバレ 考察 結末'
  },
  {
    id: 'fantastic_four_fs',
    titleJa: 'ファンタスティック・フォー：ファースト・ステップス',
    titleEn: 'The Fantastic Four: First Steps',
    type: 'movie',
    releaseDate: '2025-07-25',
    releaseOrder: 49,
    chronoOrder: 50,
    chronoSetting: '1960年代のレトロフューチャーなパラレルワールド',
    phase: 6,
    importance: 3,
    importanceReason: 'マーベル最初のコミックファミリーがついにMCU参戦。フェーズ6の幕開けを果たし、宇宙の脅威ギャラクタスが襲来。',
    synopsis: '1960年代のパラレル世界に生きる天才科学者リード・リチャーズら4人は、宇宙線を浴びて超能力を取得し「ファンタスティック・フォー」を結成。宇宙を喰らう魔神ギャラクタスと、その使者シルバーサーファーから世界を救う。',
    directorOrCreator: 'マット・シャックマン',
    durationOrEpisodes: '2時間10分',
    officialUrl: 'https://marvel.disney.co.jp/movie/fantastic-four',
    explanationUrlQuery: 'ファンタスティックフォー ファーストステップス ネタバレ 考察 結末'
  },
  {
    id: 'ironheart',
    titleJa: 'アイアンハート',
    titleEn: 'Ironheart',
    type: 'drama',
    releaseDate: '2025-09-03',
    releaseOrder: 50,
    chronoOrder: 51,
    chronoSetting: '2026年（ワカンダ・フォーエバーのその後）',
    phase: 5,
    importance: 2,
    importanceReason: 'リリ・ウィリアムズが独自のアイアンマンスーツを極限まで発展させていく物語。ハイテクと魔法・魔術の対立。',
    synopsis: 'MITの天才学生リリは、トニー・スタークの後を追うように自家製高性能アーマースーツを開発。かつてワカンダで戦った彼女は、今度はシカゴを舞台にテクノロジーと漆黒のマジックを極めたヴィラン「ザ・フード」と対峙する。',
    directorOrCreator: 'チナカ・ホッジ',
    durationOrEpisodes: '全6話',
    officialUrl: 'https://marvel.disney.co.jp/movie/ironheart',
    explanationUrlQuery: 'アイアンハート ドラマ ネタバレ 考察'
  },
  {
    id: 'avengers_doomsday',
    titleJa: 'アベンジャーズ：ドゥームズデイ',
    titleEn: 'Avengers: Doomsday',
    type: 'movie',
    releaseDate: '2026-05-01',
    releaseOrder: 51,
    chronoOrder: 52,
    chronoSetting: '2026年（マルチバース衝突の最高潮、ドゥームの宣戦布告）',
    phase: 6,
    importance: 3,
    importanceReason: 'ルッソ兄弟が監督に復帰。ロバート・ダウニー・Jrが全く違う「ドクター・ドゥーム」役として衝撃復帰を果たすフェーズ6超弩級クライマックス。',
    synopsis: 'マルチバース支配を巡り、別世界から最凶最悪の帝王「ビクター・フォン・ドゥーム（ドクター・ドゥーム）」が襲来。アベンジャーズ、ファンタスティック・フォー、宇宙の守護者たちが再び結集し、この最大の破壊者に立ち向かう。',
    directorOrCreator: 'アンソニー＆ジョー・ルッソ',
    durationOrEpisodes: '2時間35分',
    officialUrl: 'https://marvel.disney.co.jp/movie/avengers-doomsday',
    explanationUrlQuery: 'アベンジャーズ ドゥームズデイ ネタバレ 考察 サノスとの違い'
  },
  {
    id: 'avengers_secret_wars',
    titleJa: 'アベンジャーズ：シークレット・ウォーズ',
    titleEn: 'Avengers: Secret Wars',
    type: 'movie',
    releaseDate: '2027-05-07',
    releaseOrder: 52,
    chronoOrder: 53,
    chronoSetting: '時間と空間が衝突・統合された究極の「バトルワールド」',
    phase: 6,
    importance: 3,
    importanceReason: '『エンドゲーム』を超えるMCU最大最後のオールスター・ムービー。マルチバースの戦いが臨界点を迎え、世界が再編される。',
    synopsis: 'すべてのマルチバースがインカージョン（次元衝突）により完全に消滅し、残った時間軸の断片をドゥームが繋ぎ合わせた世界「バトルワールド」。デッドプール、ウルヴァリン、スパイダーマンら全ヒーローが生き残りを賭けて激突。',
    directorOrCreator: 'アンソニー＆ジョー・ルッソ',
    durationOrEpisodes: '3時間近く',
    officialUrl: 'https://marvel.disney.co.jp/movie/avengers-secret-wars',
    explanationUrlQuery: 'アベンジャーズ シークレットウォーズ ネタバレ 考察 伏線回収'
  }
];
